In [1]:
import requests
import pandas as pd
import json
yelp_key = "ujlA1jaHG5iEFdXE5RBlM4acSene7FFevF8WvCqnp_nxM0IXyhxbjQYsSASQR2GNA_xfHyjJj43bis9qTVyCM3u9KmJaLMyBoOUrfu1UPsEmaWkD0kaW_Ydq4s-fXnYx"

yelp_base_url = "https://api.yelp.com/v3/businesses/"
yelp_key = {'Authorization': 'Bearer %s' % yelp_key}
yelp_key

{'Authorization': 'Bearer ujlA1jaHG5iEFdXE5RBlM4acSene7FFevF8WvCqnp_nxM0IXyhxbjQYsSASQR2GNA_xfHyjJj43bis9qTVyCM3u9KmJaLMyBoOUrfu1UPsEmaWkD0kaW_Ydq4s-fXnYx'}

In [2]:
checkin_data = pd.read_csv("YelpData/yelp_checkin.csv")

In [3]:
#response = requests.get(yelp_base_url + "mU3vlAVzTxgmZUu6F4XixA", headers = yelp_key).json()

In [4]:

for index, row in checkin_data.iterrows():
    business_id = row['business_id']
    result = requests.get(yelp_base_url + business_id, headers = yelp_key).json()
    test_list = ""
    try:
        checkin_data.loc[index, 'Name'] = result['name']
        checkin_data.loc[index, 'City'] = result['location']['city']
        checkin_data.loc[index, 'State'] = result['location']['state']
        #checkin_data.loc[index, 'Category'] = result['categories'][0]['title']
        for i in range(len(result["categories"])):
            test_list = test_list + " " + str(result["categories"][i]["alias"])
        checkin_data.loc[index, "Category"] = test_list
        checkin_data.loc[index, 'Rating'] = result['rating']
        checkin_data.loc[index, 'Review Count'] = result['review_count']
    except:
        print("Restaurant does not have enough data.")

Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.
Restaurant does not have enough data.

In [10]:
checkin_data = checkin_data.dropna() #removing Null Values
#cities las vegas, charlotte, toronto
#checkin_data['City']
project_data = checkin_data.loc[((checkin_data['City'] == 'Las Vegas') | (checkin_data['City'] == 'Charlotte') | (checkin_data['City'] == 'Toronto'))]
project_data = project_data.rename(columns = {'business_id': 'Business ID',
                                             'total_checkin': 'Total Check-Ins',
                                             '01': '2019-01',
                                             '02': '2019-02',
                                             '03': '2019-03',
                                             '04': '2019-04',
                                             '05': '2019-05',
                                             '06': '2019-06',
                                             '07': '2019-07',
                                             '08': '2019-08',
                                             '09': '2019-09',
                                             '10': '2019-10',
                                             '11': '2019-11',
                                             '12': '2019-12'})
checkin_data.to_csv("YelpData/unfiltered_data.csv")
project_data.to_csv("YelpData/filtered_data.csv")
project_data

,Business ID,Total Check-Ins,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,Name,City,State,Category,Rating,Review Count
0,-1m9o3vGRA8IBPNvNqKLmA,218,19,20,13,17,20,14,18,29,19,24,19,6,Bavette's Steakhouse & Bar - Temporarily Closed,Las Vegas,NV,steak bars newamerican,4.5,542.0
2,-9dmhyBvepc08KPEHlEM0w,247,6,11,10,24,25,22,41,44,25,26,9,4,CN Tower,Toronto,ON,landmarks observatories,4.0,782.0
3,-ADtl9bLp8wNqYX1k3KuxA,225,25,27,22,22,21,7,18,19,18,15,24,7,Ichi Ramen House,Las Vegas,NV,ramen asianfusion sushi,4.0,685.0
6,-LzUYsR54hd8cCiYXTquRA,229,41,32,33,19,21,17,15,15,14,9,11,2,Medley Buffet,Las Vegas,NV,buffets,3.0,528.0
8,-Qkx7W0itbAApcG5lJuMFQ,1048,83,66,115,93,121,78,113,127,85,59,75,33,Jaburritos,Las Vegas,NV,japanese sushi seafood,4.5,634.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1203,zY-1U4rMVjMN_7gCjXJvow,228,0,13,2,15,69,49,35,15,4,15,11,0,Vegas Discount Nutrition Superstore,Las Vegas,NV,vitaminssupplements healthmarkets,4.0,3.0
1204,zaxK3ea92mvEBRy-jttngg,460,27,25,52,35,42,38,84,32,29,31,45,20,Virgil's Real BBQ - Las Vegas,Las Vegas,NV,bars bbq breakfast_brunch,4.0,696.0
1206,zgQHtqX0gqMw1nlBZl2VnQ,497,7,11,45,81,44,48,44,47,41,63,52,14,Momofuku Noodle Bar,Toronto,ON,ramen noodles,3.0,1031.0
1207,zhj1rDmdmliip6PMYudQug,341,14,24,38,32,53,36,42,36,21,22,16,7,Pedi Lounge N Nails,Las Vegas,NV,waxing othersalons eyelashservice,4.5,340.0
1210,zx_j6OuuHHa2afVoAZuLpA,241,31,22,33,31,18,26,19,9,16,17,13,6,what's Crepe,Las Vegas,NV,creperies desserts waffles,4.5,218.0